# Generated by Django 5.0.6 on 2024-07-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userprofile_alter_food_user_id_alter_meal_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
